"""
Unit and Integration Tests for OpenAIProvider Adapter.

Verifies:
- OpenAIProvider construction and configuration
- Missing API key error normalization
- Successful chat completion translation and normalization
- API error, timeout, and malformed response normalization
- Model override per invocation request
- Role independence (architect vs reviewer)
- BridgeCore integration with OpenAIProvider
- Zero leakage of OpenAI SDK objects into InvocationResult
"""
from unittest.mock import MagicMock
import pytest

from jester_bridge.contracts import (
    InvocationRequest,
    InvocationResult,
    InvocationStatus,
)
from jester_bridge.core import BridgeCore
from jester_bridge.config import BridgeConfig
from jester_bridge.agent import AgentProfile
from jester_bridge.protocol import Task
from jester_bridge.roles import Role
from jester_bridge.openai_provider import OpenAIProvider


def _create_mock_chat_completion(
    content="This is a test response generated by the model.\n\nAdditional details here.",
    model="gpt-4o",
    prompt_tokens=150,
    completion_tokens=40,
    total_tokens=190,
    finish_reason="stop",
    response_id="chatcmpl-mock-12345",
):
    """Helper to build a mock ChatCompletion object mimicking OpenAI SDK response."""
    message = MagicMock()
    message.content = content

    choice = MagicMock()
    choice.message = message
    choice.finish_reason = finish_reason

    usage = MagicMock()
    usage.prompt_tokens = prompt_tokens
    usage.completion_tokens = completion_tokens
    usage.total_tokens = total_tokens

    response = MagicMock()
    response.id = response_id
    response.model = model
    response.choices = [choice]
    response.usage = usage
    return response


def test_openai_provider_construction_and_properties():
    provider = OpenAIProvider(
        api_key="test-key-mock",
        default_model="o3-mini",
        timeout=30.0,
        supported_capabilities={"planning", "reasoning", "repository_read"},
    )
    assert provider.provider_id == "openai"
    assert provider.default_model == "o3-mini"
    assert "planning" in provider.get_supported_capabilities()
    assert "repository_write" not in provider.get_supported_capabilities()
    assert provider.health_check() is True


def test_openai_provider_health_check_without_key(monkeypatch):
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    provider = OpenAIProvider(api_key=None)
    assert provider.health_check() is False


def test_openai_provider_missing_key_invocation(monkeypatch):
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    provider = OpenAIProvider(api_key=None)

    req = InvocationRequest(
        request_id="req-1",
        task_id="TASK-0010",
        role="architect",
        agent_id="test-architect",
        provider="openai",
        model="gpt-4o",
        created_at="2026-09-17T00:00:00Z",
    )
    result = provider.invoke(req)
    assert result.status == InvocationStatus.FAILED
    assert "OPENAI_API_KEY is not configured" in (result.error_message or "")


def test_openai_provider_successful_invocation_and_normalization():
    mock_response = _create_mock_chat_completion(
        content="Architecture plan decomposed into 3 phases.\n\nPhase 1: Foundation.\nPhase 2: Adapters.",
        model="o3-mini-2026",
    )
    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    provider = OpenAIProvider(api_key="mock", client=mock_client)

    req = InvocationRequest(
        request_id="req-test-success",
        task_id="TASK-0004",
        role="architect",
        agent_id="chatgpt-lead",
        provider="openai",
        model="o3-mini",
        required_capabilities={"planning", "reasoning"},
        payload={"title": "Architect Feature", "goal": "Establish foundation"},
        created_at="2026-09-17T00:00:00Z",
    )

    result = provider.invoke(req)

    assert result.status == InvocationStatus.SUCCESS
    assert result.task_id == "TASK-0004"
    assert result.agent_id == "chatgpt-lead"
    assert result.provider == "openai"
    assert result.model == "o3-mini-2026"
    assert "Architecture plan decomposed" in result.summary
    assert result.error_message is None

    # Check raw metadata extraction and confirm zero SDK object leak
    assert result.raw_metadata["response_id"] == "chatcmpl-mock-12345"
    assert result.raw_metadata["prompt_tokens"] == 150
    assert result.raw_metadata["total_tokens"] == 190
    assert not hasattr(result, "choices")
    assert isinstance(result.raw_metadata, dict)

    # Verify mock client arguments
    mock_client.chat.completions.create.assert_called_once()
    call_kwargs = mock_client.chat.completions.create.call_args[1]
    assert call_kwargs["model"] == "o3-mini"
    messages = call_kwargs["messages"]
    assert len(messages) == 2
    assert messages[0]["role"] == "system"
    assert "software architect" in messages[0]["content"]
    assert messages[1]["role"] == "user"
    assert "TASK ID: TASK-0004" in messages[1]["content"]


def test_openai_provider_role_independence():
    mock_response = _create_mock_chat_completion(content="Review verdict: PASS. Acceptance criteria verified.")
    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    provider = OpenAIProvider(api_key="mock", client=mock_client)

    # Invoke as reviewer
    req_reviewer = InvocationRequest(
        request_id="req-rev-1",
        task_id="TASK-0004",
        role="reviewer",
        agent_id="chatgpt-critic",
        provider="openai",
        model="gpt-4o",
        created_at="2026-09-17T00:00:00Z",
    )
    result = provider.invoke(req_reviewer)
    assert result.status == InvocationStatus.SUCCESS

    call_kwargs = mock_client.chat.completions.create.call_args[1]
    system_prompt = call_kwargs["messages"][0]["content"]
    assert "code reviewer" in system_prompt


def test_openai_provider_api_error_normalization():
    mock_client = MagicMock()
    mock_client.chat.completions.create.side_effect = RuntimeError("500 Internal Server Error from OpenAI API")

    provider = OpenAIProvider(api_key="mock", client=mock_client)

    req = InvocationRequest(
        request_id="req-err-1",
        task_id="TASK-0004",
        role="architect",
        agent_id="chatgpt-lead",
        provider="openai",
        created_at="2026-09-17T00:00:00Z",
    )
    result = provider.invoke(req)

    assert result.status == InvocationStatus.FAILED
    assert "OpenAI API call failed" in result.summary
    assert "500 Internal Server Error" in (result.error_message or "")


def test_openai_provider_timeout_error_normalization():
    mock_client = MagicMock()
    mock_client.chat.completions.create.side_effect = TimeoutError("Request timed out after 60s")

    provider = OpenAIProvider(api_key="mock", client=mock_client)

    req = InvocationRequest(
        request_id="req-time-1",
        task_id="TASK-0004",
        role="architect",
        agent_id="chatgpt-lead",
        provider="openai",
        created_at="2026-09-17T00:00:00Z",
    )
    result = provider.invoke(req)

    assert result.status == InvocationStatus.FAILED
    assert "TimeoutError" in (result.error_message or "")


def test_openai_provider_malformed_empty_choices():
    mock_response = MagicMock()
    mock_response.choices = []  # Empty choices list
    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    provider = OpenAIProvider(api_key="mock", client=mock_client)

    req = InvocationRequest(
        request_id="req-empty-1",
        task_id="TASK-0004",
        role="architect",
        agent_id="chatgpt-lead",
        provider="openai",
        created_at="2026-09-17T00:00:00Z",
    )
    result = provider.invoke(req)

    assert result.status == InvocationStatus.FAILED
    assert "no choices returned" in (result.error_message or "")


def test_openai_provider_malformed_empty_content():
    mock_response = _create_mock_chat_completion(content="   ")  # Whitespace only
    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    provider = OpenAIProvider(api_key="mock", client=mock_client)

    req = InvocationRequest(
        request_id="req-empty-2",
        task_id="TASK-0004",
        role="architect",
        agent_id="chatgpt-lead",
        provider="openai",
        created_at="2026-09-17T00:00:00Z",
    )
    result = provider.invoke(req)

    assert result.status == InvocationStatus.FAILED
    assert "empty text response" in (result.error_message or "")


def test_bridge_core_openai_integration():
    """Validates that BridgeCore seamlessly orchestrates an OpenAIProvider."""
    mock_response = _create_mock_chat_completion(content="Decomposition completed: 2 tasks defined.")
    mock_client = MagicMock()
    mock_client.chat.completions.create.return_value = mock_response

    openai_provider = OpenAIProvider(api_key="mock", client=mock_client)

    config = BridgeConfig(
        role_bindings={"architect": "chatgpt-lead"},
        agents={
            "chatgpt-lead": AgentProfile(
                id="chatgpt-lead",
                role="architect",
                provider="openai",
                model="o3-mini",
                capabilities={"planning", "reasoning", "repository_read"},
            )
        },
    )

    core = BridgeCore(config=config, providers={"openai": openai_provider})

    task = Task(
        id="TASK-ARCH-01",
        title="Plan Architecture",
        role=Role.ARCHITECT.value,
        required_capabilities={"planning", "reasoning"},
        goal="Decompose system into modules",
    )

    result = core.dispatch(task)
    assert result.status == InvocationStatus.SUCCESS
    assert result.task_id == "TASK-ARCH-01"
    assert result.agent_id == "chatgpt-lead"
    assert result.provider == "openai"
    assert "Decomposition completed" in result.summary


def test_openai_provider_placeholder_key_rejected():
    provider = OpenAIProvider(api_key="your_openai_api_key_here")
    assert provider.health_check() is False
